apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::401085558392:role/eksctl-iot-test-nodegroup-standar-NodeInstanceRole-1V96TUVVUZ2V6
      groups:
      - system:bootstrappers
      - system:nodes
    - username: codebuild
      rolearn: arn:aws:iam::401085558392:role/MyEksWorkshopCodeBuildKubectlRole
      groups:
        - system:masters
