# Docker image
# # Build a Docker image to deploy, run, or push to a container registry.
# # Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: 'ytest'
  imageName: 'kenmu/frontend-sample'

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) --password $(dockerPassword) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
    cp stage.yml stage.yml.template
    envsubst < stage.yml.template > stage.yml
- task: CopyFiles@2
  inputs:
    Contents: 'stage.yml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  env:
    DOCKER_PSWD: $(dockerPassword)        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface