version: 0.2
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME}
      - "export DOCKER_IMAGE_DIGEST=$(docker pull 401085558392.dkr.ecr.ap-northeast-1.amazonaws.com/kenmu/frontend-sample | grep sha256: | sed -r \"s/^.*(sha256:[0-9a-z]+).*$/\\1/\")"
  build:
    commands:
      - envsubst < stage.yml | kubectl apply -f -
