apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-sample
  template:
    metadata:
      labels:
        app: frontend-sample
    spec:
      containers:
      - name: frontend-sample
        image: ${DOCKER_REGISTRY_URL}/kenmu/frontend-sample@${DOCKER_IMAGE_DIGEST}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-sample
spec:
  selector:
    app: frontend-sample
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer

