apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-sample
  template:
    metadata:
      labels:
        app: frontend-sample
    spec:
      containers:
      - name: frontend-sample
        image: 401085558392.dkr.ecr.ap-northeast-1.amazonaws.com/kenmu/frontend-sample:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-sample
spec:
  selector:
    app: frontend-sample
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer

